### ISSUE TITLE
error when compiling under windows/mingw

### ISSUE THREAD

**Issue by xrayer** [davidly/ntvcm#11]
Hi, trying to compile under win10 using the latest mingw
gcc version 14.2.0 (i686-win32-dwarf-rev0, Built by MinGW-Builds project)
I got error about missing _getpid
[code]
In file included from ntvcm.cxx:44:
./djltrace.hxx: In member function 'void CDJLTrace::Trace(const char*, ...)':
./djltrace.hxx:220:41: error: '_getpid' was not declared in this scope; did you mean '_getcwd'?
  220 |                              (unsigned) _getpid() );
      |                                         ^~~~~~~
      |                                         _getcwd
/
[/code]

I fixed it by adding
#ifdef _WIN32
#include <process.h>
#endif
to both .cxx files

Also somewhere should be noted it requires quite new compiler, with older mingw 10.2.0 I got much more errors about mutex and others that probably was not supported yet. 

Compiling DOS version with OpenWatcom went quite well, I just needed to edit include dir option -I.
(wcl -d0 -q -zp=1 -ml -obmr -oh -ei -oi -s -0 -xs -j -oe=160 -ol+ -ot ntvcm.cxx x80.cxx -bcl=DOS -k8192 -fe=ntvcmdos.exe -DWATCOM -DNDEBUG -lr -I.)

**Comment by davidly** [comment]
Thanks for both pointing out the problems and providing fixes! I'll update the code to match.

**Comment by davidly** [comment]
I pushed changes to fix these. For process.h, I put it in djltrace.hxx instead of the two .cxx files. Thanks again!
