### ISSUE TITLE
Return !0 on HALT

### ISSUE THREAD

**Issue by Kroc** [davidly/ntvcm#6]
I'm writing a Z80 assembler in Z80 (https://github.com/Kroc/v80) with the goal of having 8-bit software producible on both PC and 8-bit systems rather than having separate toolchains for both. Part of this will be self-assembling on PC via CP/M emulation. Currently I've been using RunCPM (https://github.com/MockbaTheBorg/RunCPM) which is more of a self-contained emulator than a build tool and lacks methods for automation or using it as part of a build script, like NTVCM.

Firstly, thank you for NTVCM, it's incredible and exactly what I'm looking for. I have only one issue and that's the use of the Z80 halt instruction. When this is hit in my code, RunCPM can break into a debugger. ~~On NTVCM, the executable holds for a key press, but that impacts running NTVCM as part of the build script.~~ A mistake on my part, it does exit immediately, but with an errorlevel of 0

Could you please make NTVCM return a non-zero error code when it hits a HALT, so that I can detect that the program didn't complete and instead launch the binary with RunCPM to use the debugger there. If this should impact current expected behaviour, please consider a switch, like `-h` to set the HALT behaviour.

Kind regards,
Kroc Camen.

**Comment by davidly** [comment]
I like this idea!

I've pushed a change so if execution ends with a halt instruction NTVCM returns 1 instead of 0. No switch required.

Thanks
