### ISSUE TITLE
Don't print days, hours, minutes & seconds if they're 0

### ISSUE THREAD

**Issue by Kroc** [davidly/ntvcm#7]
![image](https://github.com/davidly/ntvcm/assets/142650/8d1f4593-dcf7-4b85-a684-86bcfae2fdfd)

**Comment by davidly** [comment]
more of a feature than a bug :) I've pushed a slightly different change so if days/hours/minutes are 0 it only shows milliseconds.

**Comment by Kroc** [comment]
Thanks. Great feature, I can finally tell if a small change I make to the code has measurable difference on cycles executed!
