### ISSUE TITLE
Allow Z80 code to provide a non-zero exit value

### ISSUE THREAD

**Issue by Kroc** [davidly/ntvcm#9]
This is besides HALT; for example I want my Z80 assembler to be able to return a non-zero value when there's an assembly error (but the assembler itself hasn't crashed). CP/M3 has a BDOS call for this (#108), but 2.2 does not (perhaps secretly support this call?). Since you can't guarantee what existing historical CP/M software might set the registers to upon exit, this may have to be opt-in (a switch?) and then the value of register A (or E?) is returned when a JP 0 / RST 0 or BDOS function 0 call is made. The alternative could be a write to a RAM address that can safely assume to be untouched by historical code.

**Comment by davidly** [comment]
This seems useful. 

I added a new non-standard BDOS function 111. Register e is treated as a signed integer that's returned from NTVCM provided execution didn't end with a HALT.

**Comment by Kroc** [comment]
Function 111 is already a CP/M3 function, this wouldn't play well if you or someone else ends up adding CP/M3 support in the future). If you are going to use a non-2.2 BDOS call, then use 108: https://www.seasip.info/Cpm/bdos.html#108 (I need to check what CP/M 2.2 does when you make invalid BDOS calls...)

**Comment by Kroc** [comment]
Also, BDOS call 0 is supposedly rarely used as you can just RST / JP 0, so it serves purpose as an intentional exit with a code for newer software being written

**Comment by davidly** [comment]
I thought about that, but NTVCM is a CP/M 2.2 emulator with some non-standard additions. 108 is already used for something else. If someone wants to add CP/M3 they can fork the repo and have fun :)

**Comment by davidly** [comment]
It may make sense to implement this at some point, but are there any real-world apps that require this behavior? I intentionally coded NTVCM to respond to real-world apps rather than implemented it to specs. I haven't found any apps that send invalid calls and expect responses.

**Comment by davidly** [comment]
> > I thought about that, but NTVCM is a CP/M 2.2 emulator with some non-standard additions. 108 is already used for something else. If someone wants to add CP/M3 they can fork the repo and have fun :)
> 
> Ah, well I'm thinking of software written to work on both CP/M 2 & 3, having the same BDOS call for return value, at least for NTVCM reduces complexity and the need for conditional compilations

Fair, but the BDOS extension # is already taken for NTVCM. I don't want to break for force a recompile of apps.

**Comment by Kroc** [comment]
Well in my case I'm trying to use self-developed CP/M software as if it were any other command-line application, without the concept of an emulated/simulated environment showing through. Parameters go in, result comes out; the fact it's a z80 binary is by-the-by as far as the build script is concerned. This allows for software to be built on PC in the manner expected, but also be reproducible on 8-bit hardware -- this is a very different concept from running old software in an emulator, and exactly where RunCPM falls down in this task.

**Comment by davidly** [comment]
> Well in my case I'm trying to use self-developed CP/M software as if it were any other command-line application, without the concept of an emulated/simulated environment showing through. Parameters go in, result comes out; the fact it's a z80 binary is by-the-by as far as the build script is concerned. This allows for software to be built on PC in the manner expected, but also be reproducible on 8-bit hardware -- this is a very different concept from running old software in an emulator, and exactly where RunCPM falls down in this task.

You're unblocked, right? The only issue I see is that your code wouldn't work on a CP/M 3 machine as well since the bdos function to set the exit code and semantic are different. Is that accurate?

**Comment by Kroc** [comment]
I don't understand what you mean by unblocked?

Actual scripting of the build process would be fundamentally different on real hardware -- I haven't really go to that stage yet, as there's little call to automate the entire thing in quite the same way I'm using VSCode to build and test after every save; there's no multi-tasking for one. CP/M has a primitive form of batch scripting, but in the long term, a custom program specifically for doing a multi-stage build would be required on real hardware.

**Comment by davidly** [comment]
> I don't understand what you mean by unblocked?
> 
> Actual scripting of the build process would be fundamentally different on real hardware -- I haven't really go to that stage yet, as there's little call to automate the entire thing in quite the same way I'm using VSCode to build and test after every save; there's no multi-tasking for one. CP/M has a primitive form of batch scripting, but in the long term, a custom program specifically for doing a multi-stage build would be required on real hardware.

I mean can you make progress with NTVCM as-is?

**Comment by Kroc** [comment]
> I mean can you make progress with NTVCM as-is?

Oh yes, absolutely! The use of function 111 for a return value is awkward because my assembler is designed for CP/M 2.2 but I also occasionally test it on a CP/M 3 emulated machine, so even though on NTVCM and other CP/M 2.2 systems a 111 call would do nothing unintentional, on the CP/M 3 emulator, it will!

If you can't change the private BDOS calls, then please consider a second return-value option such as via BDOS call 0!

**Comment by davidly** [comment]
OK, I'm sure I'll break someone with this change, but 108 now behaves like cp/m 3.

**Comment by Kroc** [comment]
Fabulous, I've been able to add this to my program. Sorry, but one last thing I've noticed now that I've looked at the specifics, CP/M 3 uses the following return codes:

![image](https://github.com/davidly/ntvcm/assets/142650/f35062f0-4782-4d8f-8d40-6fc13db9e20c)

It's an odd choice, but anything less than $FEFF is considered successful. I've made my program always return $FFxx where xx is the error code from the program in expected style so as to be compatible with CP/M batch scripts that would halt on codes $FFxx. This means that the return value on HALT, 1, would be considered "successful". Could you make the return code on HALT use $FFFE "The program is terminated because of a fatal BDOS error" or $FFFF (which can never be set as a return code by function 108 as that's what's used to read the current return code). That way my Windows Batch file can use ERRORLEVEL 65280 ($FF00) to catch intentional errors. Apologies in advance for all the runabout with this issue, I'm doing something fairly new here with CP/M software by integrating it into a PC-based build chain 😳

**Comment by davidly** [comment]
I've made it return -1 (0xffff sign extended to an int) on hlt.
